"""Modèles pydantic — la source du contrat OpenAPI.

Sans eux, FastAPI génère un `/docs` qui documente des chemins et rien d'autre.
Cf. le préambule de `common.py` pour le raisonnement complet, y compris le coût
assumé (typer pousse à inventer des champs, et comment on s'en garde).
"""

from .common import (
    REPONSES_ERREUR,
    EnveloppeDictionnaire,
    ErrorEnvelope,
    ItemEnvelope,
    ListEnvelope,
    Permissif,
    invented,
    unverified,
)
from .entities import (
    Absence,
    Achat,
    ActionCrm,
    AdministratifRessource,
    Agence,
    Candidat,
    Commande,
    Contact,
    Contrat,
    Cra,
    DonneesTechniques,
    Facture,
    Frais,
    Mission,
    Opportunite,
    Paiement,
    Pole,
    ProfilProjet,
    ProfilRessource,
    Projet,
    Ressource,
    Role,
    Societe,
    Temps,
    TransactionBancaire,
    UniteOperationnelle,
    UtilisateurCourant,
)

__all__ = [
    "REPONSES_ERREUR",
    "Absence",
    "Achat",
    "ActionCrm",
    "AdministratifRessource",
    "Agence",
    "Candidat",
    "Commande",
    "Contact",
    "Contrat",
    "Cra",
    "DonneesTechniques",
    "EnveloppeDictionnaire",
    "ErrorEnvelope",
    "Facture",
    "Frais",
    "ItemEnvelope",
    "ListEnvelope",
    "Mission",
    "Opportunite",
    "Paiement",
    "Permissif",
    "Pole",
    "ProfilProjet",
    "ProfilRessource",
    "Projet",
    "Ressource",
    "Role",
    "Societe",
    "Temps",
    "TransactionBancaire",
    "UniteOperationnelle",
    "UtilisateurCourant",
    "invented",
    "unverified",
]
